language: node_js
node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - yarn global add codecov

install:
  - yarn

script:
  - yarn test
  - yarn build
  - yarn test:size

after_success:
  - codecov
